stages:
  - update_master

# 变量
variables:
  SOURCE_CODE_PATH: "/data/Source_Code"
  PROJECT_NAME: "imageText-pc"

before_script:
  - echo "自动化发布分两步：1. 自动化编译; 2. 自动化部署."

update_product_env:
  stage: update_master
  script:
    - cd ${SOURCE_CODE_PATH}/${PROJECT_NAME}
    - git pull origin master
    - rm -rf node_modules && npm install --unsafe-perm
    - npm run build
    - if [ -f rshealth.tkhealthcare.com.tar.gz ]; then
    -   rm -rf rshealth.tkhealthcare.com.tar.gz
    - fi
    - mv dist rshealth.tkhealthcare.com && tar zcf rshealth.tkhealthcare.com.tar.gz rshealth.tkhealthcare.com && rm -rf rshealth.tkhealthcare.com
    #- ssh 10.130.104.147 "cd /data/web_bak; sh .update_imageText-pc.sh"
  only:
    - master
  tags:
    - tags_of_mavenserver_imageText-pc_master
